### PR TITLE
bugfix state class measurement

### PR DESCRIPTION
**Pull request by stigvi**
Removed state class measurement from the level sensor as it seems HA does not display history correct with this attribute on text sensors

### CODE REVIEW

**Review by Limych — CHANGES_REQUESTED** [review]
Please add unit tests to your code and format your PR according to the original template.

**Comment by nareddyt** [comment]
https://github.com/Limych/ha-iaquk/pull/116 is a continuation of this PR

**Comment by billmaterial** [comment]
Updated to core 2023.5.3 and it does not work at all now, error in configuration.yaml:
Component error: iaquk - Exception importing custom_components.iaquk

**Comment by Limych** [comment]
Thanks :heart: 

Fixed in #116

**Pull request closed without merging**
